basePath: /
definitions:
  utils.Response:
    properties:
      code:
        description: 错误码
        type: integer
      data:
        description: 数据
      message:
        description: 错误信息
        type: string
    type: object
  validation.UserChangePasswordDTO:
    properties:
      new_password:
        maxLength: 32
        minLength: 6
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  validation.UserListResponseDTO:
    properties:
      items:
        description: 用户列表
        items:
          $ref: '#/definitions/validation.UserResponseDTO'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  validation.UserResponseDTO:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      last_login_at:
        type: string
      nickname:
        type: string
      status:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  validation.UserUpdateDTO:
    properties:
      email:
        type: string
      id:
        type: integer
      nickname:
        maxLength: 32
        type: string
      status:
        enum:
        - 0
        - 1
        - 2
        type: integer
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - id
    type: object
host: localhost:9999
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a Gin API template.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin API Template
  version: "1.0"
paths:
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: 支持分页、排序和关键词搜索的用户列表查询接口
      parameters:
      - default: 1
        description: 页码，从1开始计数
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页记录数，默认10条
        in: query
        name: page_size
        type: integer
      - description: 搜索关键词，支持用户名、邮箱和昵称模糊搜索
        in: query
        name: keyword
        type: string
      - default: id
        description: 排序字段，支持id、username、created_at等
        in: query
        name: order_by
        type: string
      - default: desc
        description: '排序方向: asc(升序)或desc(降序)'
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户列表数据，包含总数和分页记录
          schema:
            $ref: '#/definitions/validation.UserListResponseDTO'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: 未授权，请先登录
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - Bearer: []
      summary: 用户列表查询
      tags:
      - 用户管理
  /api/v1/users/{id}:
    delete:
      consumes:
      - application/json
      description: 根据用户ID删除指定用户记录
      parameters:
      - description: 用户ID (必填)
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: 用户ID格式错误
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: 未授权，请先登录
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: 无权删除此用户
          schema:
            $ref: '#/definitions/utils.Response'
        "404":
          description: 用户不存在
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - Bearer: []
      summary: 删除用户
      tags:
      - 用户管理
    get:
      consumes:
      - application/json
      description: 根据用户ID获取用户的详细资料信息
      parameters:
      - description: 用户ID (必填)
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 用户详细信息
          schema:
            $ref: '#/definitions/validation.UserResponseDTO'
        "400":
          description: 用户ID格式错误
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: 未授权，请先登录
          schema:
            $ref: '#/definitions/utils.Response'
        "404":
          description: 用户不存在
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - Bearer: []
      summary: 获取单个用户信息
      tags:
      - 用户管理
    put:
      consumes:
      - application/json
      description: 根据用户ID更新用户资料，支持部分字段更新
      parameters:
      - description: 用户ID (必填)
        in: path
        name: id
        required: true
        type: integer
      - description: 用户信息更新内容
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/validation.UserUpdateDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 更新后的用户信息
          schema:
            $ref: '#/definitions/validation.UserResponseDTO'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: 未授权，请先登录
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: 无权限操作此用户
          schema:
            $ref: '#/definitions/utils.Response'
        "404":
          description: 用户不存在
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - Bearer: []
      summary: 更新用户信息
      tags:
      - 用户管理
  /api/v1/users/change-password:
    post:
      consumes:
      - application/json
      description: 修改当前登录用户的密码，需要提供旧密码和新密码
      parameters:
      - description: 密码修改数据，包含旧密码和新密码
        in: body
        name: passwordData
        required: true
        schema:
          $ref: '#/definitions/validation.UserChangePasswordDTO'
      produces:
      - application/json
      responses:
        "200":
          description: 密码修改成功
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/utils.Response'
        "401":
          description: 未授权，请先登录
          schema:
            $ref: '#/definitions/utils.Response'
        "403":
          description: 旧密码验证失败
          schema:
            $ref: '#/definitions/utils.Response'
        "422":
          description: 新密码格式不符合要求
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - Bearer: []
      summary: 修改用户密码
      tags:
      - 用户管理
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
